[build]
  command = "bundle exec middleman build"
  publish = "build/"
[[redirects]]
  from = "https://flashover.netlify.com/*"
  to = "https://www.flashover.blog/:splat"
  status = 301
  force = true
